# ============================================
# Stage 1: Build Frontend Assets
# ============================================
FROM node:26-alpine AS asset-builder

WORKDIR /build

# Copy package files, lockfile, and build script
COPY package.json package-lock.json ./
COPY copy-assets.js .

# Install exact dependencies from lockfile
RUN npm ci --production

# Create vendor directory structure
RUN mkdir -p src/static/vendor

# Execute asset copy script
RUN npm run build-assets

# ============================================
# Stage 2: Development (adds faker, pytest; runs as root for bind mounts)
# ============================================
FROM python:3.14-slim AS dev

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgobject-2.0-0 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libcairo2 \
    libgdk-pixbuf-xlib-2.0-0\
    libffi-dev \
    shared-mime-info \
    fonts-liberation \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# The entrypoint runs `flask db upgrade` and the seed commands; the flask CLI needs to
# know where the app is, and the image must not depend on a .env file for that.
ENV FLASK_APP=run.py

COPY requirements-dev.txt requirements.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY . .
COPY --from=asset-builder /build/src/static/vendor /app/src/static/vendor

# Install enterprise plugin at build time if present (dev only)
RUN if [ -d /app/opsdeck-enterprise ]; then \
        pip install --no-cache-dir -e /app/opsdeck-enterprise; \
    fi \
    && chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

# ============================================
# Stage 3: Production image (last on purpose: a bare `docker build .` builds this)
# ============================================
FROM python:3.14-slim AS production

# Install system dependencies for WeasyPrint (PDF generation)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgobject-2.0-0 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libcairo2 \
    libgdk-pixbuf-xlib-2.0-0\
    libffi-dev \
    shared-mime-info \
    fonts-liberation \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# The entrypoint runs `flask db upgrade` and the seed commands; the flask CLI needs to
# know where the app is, and the image must not depend on a .env file for that.
ENV FLASK_APP=run.py

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run as an unprivileged user. uid 1000 is what the Helm chart's fsGroup expects so
# that mounted volumes (logs, attachments) are writable.
RUN groupadd --gid 1000 opsdeck \
    && useradd --uid 1000 --gid opsdeck --create-home --shell /usr/sbin/nologin opsdeck

# Copy the rest of the application's code into the container at /app
COPY --chown=opsdeck:opsdeck . .

# Overwrite vendor static files with those generated by Node
COPY --from=asset-builder --chown=opsdeck:opsdeck /build/src/static/vendor /app/src/static/vendor

# The directories the app writes to must exist and belong to the runtime user before any
# volume is mounted over them, so a run without volumes works too.
RUN chmod +x ./entrypoint.sh \
    && mkdir -p /app/logs /app/data/attachments \
    && chown -R opsdeck:opsdeck /app/logs /app/data

USER opsdeck
ENV HOME=/home/opsdeck

# /health answers without authentication and is exempt from the HTTPS redirect.
HEALTHCHECK --interval=30s --timeout=5s --start-period=120s --retries=3 \
    CMD python3 -c "import sys, urllib.request; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:5000/health', timeout=4).status == 200 else 1)"

# Set the entrypoint for the container
ENTRYPOINT ["./entrypoint.sh"]
