"""Add specific renewal days

Revision ID: 59a41e854865
Revises: 4d47caedcd09
Create Date: 2025-09-09 07:41:04.639902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a41e854865'
down_revision = '4d47caedcd09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_renewal_day', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('monthly_renewal_day')

    # ### end Alembic commands ###
