"""Add is_archived to Service model

Revision ID: 8cadfab2c2b9
Revises: 5bed3661e58e
Create Date: 2025-09-08 19:55:07.725619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cadfab2c2b9'
down_revision = '5bed3661e58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
